"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Loader2, Star, X } from "lucide-react";
import { getListingReviews, getReviewSummary, type ListingReview } from "@/services/listingService";

function bar(label: string, value: number) { return <div className="flex items-center gap-3 text-xs"><span className="w-24 text-slate-600">{label}</span><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-slate-900" style={{ width: `${Math.min(100, value * 20)}%` }} /></div><span className="w-7 text-right text-slate-500">{value.toFixed(1)}</span></div>; }
function Avatar({ name, src }: { name: string; src?: string }) { return src ? <img src={src} alt={name} className="h-10 w-10 rounded-full object-cover" /> : <div className="flex h-10 w-10 items-center justify-center rounded-full bg-rose-100 font-semibold text-rose-700">{name.charAt(0)}</div>; }

export function ListingReviews({ listingId }: { listingId: string }) {
  const [allOpen, setAllOpen] = useState(false);
  const summary = useQuery({ queryKey: ["review-summary", listingId], queryFn: () => getReviewSummary(listingId) });
  const reviews = useQuery({ queryKey: ["listing-reviews", listingId], queryFn: () => getListingReviews(listingId) });
  const reviewPage = reviews.data as { content?: ListingReview[]; totalElements?: number } | undefined;
  const reviewList = reviewPage?.content || [];
  const rating = Number(summary.data?.overallAverage || 0);
  const total = Number(summary.data?.totalReviews || reviewPage?.totalElements || 0);
  if (summary.isLoading || reviews.isLoading) return <section className="border-b border-slate-200 py-8"><div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Loading reviews...</div></section>;
  if (summary.isError || reviews.isError) return <section className="border-b border-slate-200 py-8"><p className="text-sm text-slate-500">Reviews are temporarily unavailable.</p></section>;
  return <section className="border-b border-slate-200 py-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold"><Star className="mr-2 inline h-5 w-5 fill-slate-900" />{rating ? rating.toFixed(1) : "New"} · {total} reviews</h2>{total > reviewList.length && <button type="button" onClick={() => setAllOpen(true)} className="text-sm font-semibold underline">See all {total} reviews</button>}</div>{total > 0 && <div className="mt-6 grid gap-8 rounded-2xl border border-slate-200 p-5 sm:grid-cols-2"><div className="flex items-center gap-4"><span className="text-4xl font-semibold">{rating.toFixed(1)}</span><span className="flex text-amber-400">{[1, 2, 3, 4, 5].map((star) => <Star key={star} className="h-4 w-4 fill-current" />)}</span></div><div className="space-y-2">{bar("Cleanliness", Number(summary.data?.cleanlinessAverage || 0))}{bar("Location", Number(summary.data?.locationAverage || 0))}{bar("Value", Number(summary.data?.valueAverage || 0))}{bar("Check-in", Number(summary.data?.locationAverage || 0))}</div></div>}{reviewList.length ? <div className="mt-7 grid gap-7 sm:grid-cols-2">{reviewList.slice(0, 4).map((review) => <article key={review.id}><div className="flex items-center gap-3"><Avatar name={review.reviewerName} src={review.reviewerAvatarUrl} /><div><p className="font-semibold">{review.reviewerName}</p><p className="text-xs text-slate-500">{new Date(review.date || review.createdAt || "").toLocaleDateString(undefined, { month: "long", year: "numeric" })}</p></div></div><p className="mt-4 line-clamp-3 text-sm leading-6 text-slate-700">{review.comment}</p></article>)}</div> : <p className="mt-5 text-sm text-slate-500">No reviews yet. Be the first to share your stay.</p>}{total > reviewList.length && <button type="button" onClick={() => setAllOpen(true)} className="mt-6 rounded-full border border-slate-900 px-4 py-2 text-sm font-semibold">See all {total} reviews</button>}{allOpen && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 sm:p-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">All reviews</h2><button type="button" onClick={() => setAllOpen(false)} aria-label="Close reviews"><X /></button></div><div className="mt-6 space-y-7">{reviewList.map((review) => <article key={review.id} className="border-b border-slate-200 pb-6"><div className="flex items-center gap-3"><Avatar name={review.reviewerName} src={review.reviewerAvatarUrl} /><div><p className="font-semibold">{review.reviewerName}</p><p className="text-xs text-slate-500">{new Date(review.date || review.createdAt || "").toLocaleDateString()}</p></div></div><p className="mt-3 text-sm leading-6 text-slate-700">{review.comment}</p></article>)}</div></div></div>}</section>;
}
